// Generated by Copilot
// ...existing code...

function getGoogleMicrosoftOAuthConfig() {
  const envPath = path.join(__dirname, "../../", ".env");
  if (!fs.existsSync(envPath)) return { enabled: false };

  const microsoftConfig = {
    enabled: !!process.env.MICROSOFT_CLIENT_ID && !!process.env.MICROSOFT_CLIENT_SECRET && !!process.env.MICROSOFT_REDIRECT_URI,
    clientId: process.env.MICROSOFT_CLIENT_ID,
    clientSecret: process.env.MICROSOFT_CLIENT_SECRET,
    redirectUri: process.env.MICROSOFT_REDIRECT_URI,
    tenantId: process.env.MICROSOFT_TENANT_ID || 'common'
  };

  return microsoftConfig;
}

// ...existing code...

module.exports = {
  // ...existing exports...
  getGoogleMicrosoftOAuthConfig,
};