// Generated by Copilot
import { useEffect, useState } from 'react';
import System from '@/models/system';
import { useTranslation } from 'react-i18next';
import microsoftLogo from '@/media/microsoft.svg';

export default function MicrosoftLoginButton() {
  const [enabled, setEnabled] = useState(false);
  const [loginUrl, setLoginUrl] = useState(null);
  const { t } = useTranslation();

  useEffect(() => {
    async function checkMicrosoftOAuth() {
      const { enabled, loginUrl } = await System.getMicrosoftOAuthStatus();
      setEnabled(enabled);
      setLoginUrl(loginUrl);
    }
    checkMicrosoftOAuth();
  }, []);

  if (!enabled || !loginUrl) return null;

  return (
    <div className="w-full flex justify-center items-center my-2">
      <a
        href={loginUrl}
        className="flex items-center justify-center gap-x-2 w-full max-w-[300px] bg-theme-secondary hover:bg-theme-secondary-hover text-white font-medium rounded-lg text-sm px-5 py-2.5 transition-all duration-300"
      >
        <img src={microsoftLogo} alt="Microsoft Logo" className="w-5 h-5" />
        {t('login.multi-user.microsoft')}
      </a>
      <div className="text-theme-text-secondary text-xs mt-2">
        {t('login.multi-user.microsoft-description')}
      </div>
    </div>
  );
}