// Generated by Copilot
import React from 'react';
import MicrosoftIcon from '@/media/microsoft.svg';
import { useTranslation } from "react-i18next";
import System from '@/models/system';

export default function MicrosoftLogin() {
  const { t } = useTranslation();
  const [loginUrl, setLoginUrl] = React.useState(null);

  React.useEffect(() => {
    async function fetchLoginUrl() {
      const { enabled, loginUrl } = await System.microsoftOAuthEnabled();
      if (enabled && loginUrl) {
        setLoginUrl(loginUrl);
      }
    }
    fetchLoginUrl();
  }, []);

  if (!loginUrl) return null;
  
  return (
    <button
      onClick={() => window.location.href = loginUrl}
      className="w-full flex items-center justify-center gap-x-2 bg-[#2F2F2F] text-white py-2.5 rounded-lg hover:bg-[#444444] transition-all duration-300"
    >
      <img src={MicrosoftIcon} alt="Microsoft Logo" className="w-5 h-5" />
      <span className="text-sm">{t('login.microsoft.continue')}</span>
    </button>
  );
}