// Generated by Copilot
import React, { useState } from 'react';
import MicrosoftLogo from '@/media/microsoft-logo.png';
import System from '@/models/system';
import { useTranslation } from "react-i18next";

export default function MicrosoftLogin() {
  const { t } = useTranslation();
  const [loading, setLoading] = useState(false);

  const handleMicrosoftLogin = async () => {
    setLoading(true);
    try {
      const { enabled, loginUrl } = await System.microsoftOAuthEnabled();
      if (!enabled) {
        console.error('Microsoft OAuth is not configured');
        return;
      }
      window.location.href = loginUrl;
    } catch (error) {
      console.error('Failed to initialize Microsoft login:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={handleMicrosoftLogin}
      disabled={loading}
      className="w-full flex items-center justify-center gap-x-2 px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-button"
    >
      <img src={MicrosoftLogo} alt="Microsoft logo" className="w-5 h-5" />
      {loading ? (
        <span className="inline-block animate-spin rounded-full h-4 w-4 border-b-2 border-primary-button"></span>
      ) : (
        t('login.microsoft.button')
      )}
    </button>
  );
}